language: node_js
services: mongodb
node_js: node
deploy:
services: mongodb
  provider: heroku
  api_key:
    secure: hTpEUiCxjPcFZXAyNhNpYrQ2kPPCIDSu+z4X/SHiYMfaF2vYbjHYgeyDfUCGtpN8DpdXmnA+pvRba5R3wdjm+ojs4go0zjTdxaOAHD9nuAm6tRJxaKtqwO/xYDsUl1BLlO/BxmgceP5y12R4+QZD3FVeHyWk+2M8214aaN/EmXuTdmofAb0695X7FRgwSAtea9KGJ+IYv/UGBN7komvrKDBFFPNJZcD7w+p06H7VRS4S9wG7t17c66v4XUMFd+VdJ+De4ItpdiO+WB7nNgZ2zdTt+pTH5xAGE1J3ivSCq+iIJ//QxUdcbYL58w27s9qSU2nreZYTlek1AASP9NQKHWSYC8I6z5KsCLuklO8Ekj3RaHKNy4YmMD+NFrHabGhmPw1OfFk8pfipDCtJ8BUJewdsRd6tcsDa+ChLjJAXndVO6bWuQR1/k9UZzZX7wo7BZH3k581RRBjMZIHg/RsjAEcY5h4SCZKiLHW8GEzNN9J0QYJ5s7yHZmg2a4cuQAocfFFVt75vdXtLKWH5Msb7bOovFQfET8NqO5oo0c11rhiuAt5VVQdH6n2mFqaTM5mgRVgpKS4RCZ2MlAq11ggiHOy/XQpUo9i9yTCdIiccsdUmAxNQhNslygnX6jCI+ldHqXa0H9Zf4zuMnJMN1D3Yd6h5/6Fgh/i6+iNYWCmzZoQ=
  app: better-friend-capstone
  on:
    repo: pauldoubleyouare/BetterFriendCapstone
